/*********************************************************\
 *                                                       *
 *                     S H A M A N                       *
 *                   R E S E A R C H                     *
 *                                                       *
 *              Artificial Immune Systems                *
 *                                                       *
 *  by Johan Kaers  (johankaers@gmail.com)               *
 *  Copyright (c) 2005 Shaman Research                   *
\*********************************************************/
package org.shaman.immune.network;

import org.shaman.exceptions.LearnerException;

// *********************************************************\
// *       An Exception generated by the AIS-Engine        *
// *********************************************************/
public class DAISException extends LearnerException
{
    public DAISException(String message) {
        super(message);
    }
    
    public DAISException(Throwable throwable) {
        super(throwable);
    }

    public DAISException(String message, Throwable throwable) {
        super(message,throwable);
    }
}
